#    Gitlab CI build file
#    Docs: https://gitlab.com/help/ci/examples/php.md
#          https://gitlab.com/help/ci/yaml/README.md
#          https://gitlab.com/help/ci/README.md
#    @author    Piotr Żuralski <piotr@zuralski.net>
#    @copyright 2016 Blue Media
#    @since     2016-12-03
#    @version   2.3.3

# variables:
#   GIT_STRATEGY: fetch

# Select what we should cache between builds
cache:
  paths:
    - bin/
    - vendor/

before_script:
  - ./.config/ci/bin/os-check-software.sh
#  - ./.config/ci/bin/cleanup.sh
#  - ./.config/ci/bin/php-check-version.sh
  - ./.config/ci/bin/php-check-software.sh

after_script:
  - ./.config/ci/bin/cleanup.sh

stages:
  - test
#  - deploy

.test: &test_definition
  stage: test
  except:
    - tags
  only:
    - branches
  script:
    - ./bin/phing build:dev
#    - ./bin/phing build:prod

php-latest:
  <<: *test_definition
  image: php:fpm-alpine

php-7.2:
  <<: *test_definition
  image: php:7.2-fpm-alpine

php-7.1:
  <<: *test_definition
  image: php:7.1-fpm-alpine

php-7.0:
  <<: *test_definition
  image: php:7.0-fpm-alpine

php-5.6:
  <<: *test_definition
  image: php:5.6-fpm-alpine

php-5.5:
  <<: *test_definition
  image: php:5.5-fpm-alpine

#php-5.4:
#  <<: *test_definition
#  image: php:5.4
#  allow_failure: true
#
#php-5.3:
#  <<: *test_definition
#  image: php:5.3
#  allow_failure: true

# #post-test:
# #  stage: post-test
# #  artifacts:
# #    name: "metrics-$CI_BUILD_NAME"
# #    expire_in: 7d
# #    untracked: true
# #    when: always
# #    paths:
# #    - builds/
# #  script:
# #    - echo "ok"
# #
#
# #job_deploy-prod:
# #  image: php:7.0
# #  stage: deploy
# #  environment: prod
# #  only:
# #    - develop
# #    - master
# #  script:
# #    - ./bin/phing build:prod
# #    - ./.config/ci/bin/version-tag.sh